config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  authenticated :user do
    root 'documents#index', as: :authenticated_root
  end

  resources :documents
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :find_document, only: [:show, :edit, :update, :destroy]

	def index
		@documents = current_user.documents
	end

	def show
	end

	def new
		@document = current_user.documents.build
	end

	def create
		@document = current_user.documents.build(document_params)

		if @document.save
			redirect_to @document
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @document.update(document_params)
			redirect_to @document
		else
			render 'edit'
		end
	end

	def destroy
		@document.destroy
		redirect_to documents_path
	end

	private
		def find_document
			@document = Document.find(params[:id])
		end

		def document_params
			params.require(:document).permit(:title, :content)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_form.html.haml
= simple_form_for @document do |f|
	= f.input :title
	= f.input :content
	= f.button :submit, class: 'button	'

= link_to 'Cancel', :back

app/views/documents/edit.html.haml
.wrapper_with_padding
	%h1 Edit Document!
	= render 'form'

app/views/documents/index.html.haml
.wrapper_with_padding
	#docs.clearfix
		- unless @documents.blank?
			- current_user.documents.each do |document|
				%a{ href: (url_for [document]) }
					.doc
						%p.title= document.title
						%p.date= time_ago_in_words(document.created_at)
						%p.content= truncate(document.content, length: 50)
		- else
			%h2 Create Document!
			%p Start Creating Document and Organizing your life!
			= link_to 'Create Document', new_document_path, class: 'buton'

app/views/documents/new.html.haml
.wrapper_with_padding
		%h1 New Document!
		= render 'form'

app/views/documents/show.html.haml
.wrapper_with_padding
	#doc_show
		%h1.title= @document.title
		%p= simple_format @document.content

		.buttons
			= link_to 'Edit Document', edit_document_path(@document), class: 'button'
			= link_to 'Destroy Document', document_path(@document), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FileCabinet | Your life's work
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %header
      .header_inner
        = link_to 'FileCabinet', root_path, id: 'logo'

        %nav
          - if user_signed_in?
            = link_to 'Create Document', new_document_path
            = link_to 'Sign Out', destroy_user_session_path, method: :delete

          - else
            = link_to 'Sign In', new_user_session_path

    %p.notice= notice
    %p.alert= alert

    = yield

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 File Cabinet
		%p Your life's work. Organized, always.
		= link_to 'Enter', new_user_registration_path, class: 'button'

#callouts
	.callout_inner
		.wrapper
			.callout
				%h2 Organize
				%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

#bottom_cta
	.wrapper
		%h2 Go Ahead!
		%br
		= link_to 'Join Now', new_user_registration_path, class: 'button'